export default async () => {
  process.env.DEFAULT_SESSION_EXPIRATION = "3600";
  process.env.COOKIE_SECRET = "cookie_secret__cookie_secret";
  process.env.CACHE_SERVER = "cache_server";
  process.env.COOKIE_NAME = "cookie_name";
  process.env.COOKIE_DOMAIN = "cookie_domain";
  process.env.COOKIE_SECURE_ONLY = "cookie_secure";
  process.env.SESSION_CREATE = "off";
  process.env.LOG_LEVEL = "fatal";
  process.env.API_LOCAL_URL = "http://localhost:9333";
  process.env.CHS_API_KEY = "key1";
  process.env.EXTENSIONS_API_URL = "http://localhost:9333";
  process.env.ACCESSIBILITY_TEST_MODE = "off";
  process.env.NODE_ENV = "test";
  process.env.EXTENSIONS_PROCESSOR_API_URL = "http://localhost:9333";
  process.env.PERMISSION_NAME_DOWNLOAD = "dummy_download_permission";
  process.env.PERMISSION_NAME_VIEW = "dummy_view_permission";
  process.env.MAXIMUM_EXTENSION_REQUESTS_PER_DAY = "50";
  process.env.FEATURE_REQUEST_COUNT="off";
  process.env.FEATURE_MISSING_AUTHENTICATION_CODE="on";
  process.env.MAX_FILE_SIZE_BYTES = "10";
  process.env.PIWIK_URL = "test";
  process.env.PIWIK_SITE_ID = "test";
  process.env.SHOW_SERVICE_UNAVAILABLE_PAGE = "off";
  process.env.TOO_SOON_DAYS_BEFORE_DUE_DATE="273";
  process.env.MAX_EXTENSION_PERIOD_IN_MONTHS="12"
};
